# Change these first
owner: nightwatchcybersecurity # Your GitHub organization or username, where this repository lives
repo: icetrust_uptime_example # The name of this repository

assignees:
  - nightwatchcyber

sites:
  - name: codecov bash uploader
    url: https://icetrust_dashboard.nightwatchcybersecurity.com/data/output/codecov.json
    icon: https://about.codecov.io/wp-content/themes/codecov/assets/brand/icons/favicons/favicon-16x16.png
    __dangerous__body_down: '"verified": false'
  - name: nixos install script
    url: https://icetrust_dashboard.nightwatchcybersecurity.com/data/output/nixos.json
    icon: https://nixos.org/favicon.png
    __dangerous__body_down: '"verified": false'
  - name: rvm install script
    url: https://icetrust_dashboard.nightwatchcybersecurity.com/data/output/rvm.json
    icon: https://rvm.io/favicon.ico
    __dangerous__body_down: '"verified": false'

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: icetrust_uptime.nightwatchcybersecurity.com

  # baseUrl: /your-repo-name
  #logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg

  name: Icetrust Example Dashboard
  introTitle: "**Icetrust** example dashboard."
  introMessage: "This dashboard shows an example of how to verify shell scripts used for installation via [the icetrust project](https://github.com/nightwatchcybersecurity/icetrust). There is an alternate version here: [icetrust_dashboard.nightwatchcybersecurity.com](https://icetrust_dashboard.nightwatchcybersecurity.com/). These projects were selected from the lists found in our [dont_curl_and_bash project](https://github.com/nightwatchcybersecurity/dont_curl_and_bash)."
  navbar:
    - title: Status
      href: /
    - title: Alternate Dashboard
      href: https://icetrust_dashboard.nightwatchcybersecurity.com/
    - title: GitHub for this dashboard
      href: https://github.com/$OWNER/$REPO
    - title: Icetrust Repo
      href: https://github.com/nightwatchcybersecurity/icetrust

commitMessages:
  commitAuthorName: "Icetrust Bot"
  commitAuthorEmail: "icetrust-bot@nightwatchcybersecurity.com"

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "15 * * * *"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

